### ISSUE TITLE
Panel/podokno pro editaci

### ISSUE THREAD

**Issue by ppicha** [VenaJanoch/BakalarkaSPADEUI#21]
schovávací panel pro editaci vybraného objektu

**Comment by VenaJanoch** [comment]
Panel napřiklad jako ma Seznam na Mapach. Po kliknuti do tabulky zobrazit panel s danými informacemi o prvku. 

![vyjizdecimenu](https://user-images.githubusercontent.com/14912423/53490569-4a70fb80-3a94-11e9-873a-d43be23c1862.png)
