### ISSUE TITLE
Panel/podokno se seznamy entit

### ISSUE THREAD

**Issue by ppicha** [VenaJanoch/BakalarkaSPADEUI#22]
schovávací panel pro výběr/přidání/smazání entit, které nejdou na kanvas

**Comment by VenaJanoch** [comment]
Panel napřiklad jako ma Seznam na Mapach. Po kliknuti bud na tlacitko nebo po vyberu ze selectboxu, vyjede panel s tabulkou, ve které bude možné výběr/přidání/smazání entit, které nejdou na kanvas. Po kliknutí na řádek vyjede druhý panel, kde bude možná editace.

![hlavni okno](https://user-images.githubusercontent.com/14912423/53491033-953f4300-3a95-11e9-875e-3295e0afa331.png)
