### ISSUE TITLE
Naklikávání kritérií v editaci objektu

### ISSUE THREAD

**Issue by ppicha** [VenaJanoch/BakalarkaSPADEUI#25]
+/- na řádce: atribut, operátor, hodnota

**Comment by VenaJanoch** [comment]
Nejsem si úplně jistý funkčností operátorů.
Pokud se jedná čistě o textovou informaci je potřeba operátor? Případně "!=" "="? 
U estimated time umožnit zadat interval? 

V aplikaci jsou vytvořeny jednotlivé boxy pro operátory, plus možnost přídání atributu nebo odebrání atributu.  Tak jestli by jste se na to podíval, zda to takhle může být.  Děkuji 
![EditPanel2](https://user-images.githubusercontent.com/14912423/54318149-a899f480-45e5-11e9-8195-33c5e71a1513.PNG)
![EditPanel1](https://user-images.githubusercontent.com/14912423/54318151-a9328b00-45e5-11e9-93cc-4eeeb4507e08.PNG)

@ppicha

**Comment by ppicha** [comment]
@VenaJanoch 

Je to krok dobrým směrem, ale představoval bych si to trochu jako naklikávání podmínek pro filtry issues v Redmine.  Tzn. na začátku tam selectbox pro attribut (defaultně vybraná třeba první možnost, tzn. věcí z kanvasu např. kardinalita/četnost, kterou by měly mít všichni společno; nebo jméno, které mají asi všechny entity), selectbox pro operátor (jehož obsah se bude měnit na základě typu atributu) a pole pro hodnotu k porovnání. Následovat může (na konci stejné řádky tabulkového layoutu nebo na začátku nové) tlačítko přo přidání další řádky ve stejném formátu. Plus samozřejmě pro každou řádku tlačítko pro odebrání (nebo selectboxy, které po odškrtnutí a užití nějakého "apply" tlačítka odstraní všechny nezaškrtnuté podmínky --- jako vždy detaily implementace jsou na vás). Tak si člověk může přidat kolik chce kritérií pro jakékoli atributy, včetně více podmínek pro jeden a ten samý atribut (což ilustrovaný stav na obrázcích neumožňuje).

Pro textové atributy (name, description a další) jsou operátory is, is not, contains, not contains (nebo jinou termilogií vyjádřené ty samé koncepty).

U všech číselných, a vlastně i kalendářních, atributů (tzn. včetně estimated time) není nutný interval. Ten se obejde 2 podmínkami, každá na jedné řádce, viz celkový koncept výše.
