### ISSUE TITLE
Vizuální úprava toolbaru

### ISSUE THREAD

**Issue by ppicha** [VenaJanoch/BakalarkaSPADEUI#26]
layout, ikony, barvy, atd.

**Comment by VenaJanoch** [comment]
Návrhy aplikace
[Appka pro Venouše_modrá.pdf](https://github.com/VenaJanoch/BakalarkaSPADEUI/files/3046814/Appka.pro.Venouse_modra.pdf)
[Appka pro Venouše_zelená.pdf](https://github.com/VenaJanoch/BakalarkaSPADEUI/files/3046815/Appka.pro.Venouse_zelena.pdf)


![PajaPanel](https://user-images.githubusercontent.com/14912423/55611663-71eb7000-5786-11e9-8b32-1bf62b1bfbf1.PNG)
